<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\common.props" />
  
  <PropertyGroup>
    <TargetFrameworks>net48;netstandard2.0;net8.0;net10.0</TargetFrameworks>
    <AssemblyName>JamaaTech.Smpp.Net.Lib</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>JamaaTech.Smpp.Net.Lib</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>..\Jamaa Smpp Client.snk</AssemblyOriginatorKeyFile>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo> 
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Extensions.Logging" Version="10.0.3" />
    <PackageReference Update="Microsoft.Extensions.Logging.Console" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MinVer" Version="7.0.0" />
  </ItemGroup>

</Project>
  